name: ML Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      # 1. Lấy mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.10"

      # 3. Cài đặt các thư viện cần thiết
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pre-commit install
          pre-commit autoupdate

      # 5. Thiết lập thư mục lưu trữ EFS
      - name: Set up EFS storage directory
        run: |
          mkdir C:\efs\shared_storage\madewithml\${{ secrets.GITHUB_USERNAME }}
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
      # 6. Chạy test cho mã code
      - name: Test Code
        run: |
          $env:PYTHONPATH = "$env:PYTHONPATH;$PWD"
          $env:EXPERIMENT_NAME = "llm"
          $env:DATASET_LOC = "https://raw.githubusercontent.com/QuocHieu59/Made-With-ML/main/datasets/dataset.csv"
          python -m pytest tests/code --verbose --disable-warnings

      # 7. Chạy test cho dữ liệu
      - name: Test Data
        run: |
          $env:PYTHONPATH = "$env:PYTHONPATH;$PWD"
          $env:EXPERIMENT_NAME = "llm"
          $env:DATASET_LOC = "https://raw.githubusercontent.com/QuocHieu59/Made-With-ML/main/datasets/dataset.csv"
          pytest --dataset-loc=%DATASET_LOC% tests/data --verbose --disable-warnings

      # 8. Chạy test cho mô hình
      - name: Test Model
        run: |
          $env:PYTHONPATH = "$env:PYTHONPATH;$PWD"
          $env:EXPERIMENT_NAME = "llm"
          $env:DATASET_LOC = "https://raw.githubusercontent.com/QuocHieu59/Made-With-ML/main/datasets/dataset.csv"
          pytest tests/model --verbose --disable-warnings
