name: ML Test Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
      # 1. Lấy mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Thiết lập Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.10"

      # 3. Cài đặt các thư viện cần thiết
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pre-commit install
          pre-commit autoupdate
      # 7. Chạy test cho dữ liệu
      - name: Test Data
        run: |
          $env:PYTHONPATH = "$env:PYTHONPATH;$PWD"
          $env:EXPERIMENT_NAME = "llm"
          $env:DATASET_LOC = "https://raw.githubusercontent.com/QuocHieu59/Made-With-ML/master/datasets/dataset.csv"
          python -m pytest --dataset-loc=$env:DATASET_LOC tests/data --verbose --disable-warnings
      # 6. Chạy test cho mã code
      - name: Test Code
        run: |
          $env:PYTHONPATH = "$env:PYTHONPATH;$PWD"
          $env:EXPERIMENT_NAME = "llm"
          $env:DATASET_LOC = "https://raw.githubusercontent.com/QuocHieu59/Made-With-ML/master/datasets/dataset.csv"
          python -m pytest tests/code --verbose --disable-warnings

      # 8. Chạy test cho mô hình
      - name: Test Model
        run: |
          python -m pytest tests/model --verbose --disable-warnings

      - name: Train Model
        run: |
          $env:PYTHONPATH = "$env:PYTHONPATH;$PWD"
          $env:EXPERIMENT_NAME="llm"
          $env:DATASET_LOC="https://raw.githubusercontent.com/QuocHieu59/Made-With-ML/master/datasets/dataset.csv"
          python madewithml/tune.py --experiment-name $env:EXPERIMENT_NAME --dataset-loc $env:DATASET_LOC --num-runs 2 --num-workers 1 --cpu-per-worker 2 --gpu-per-worker 0 --num-epochs 10 --batch-size 32

      - name: Evaluation Model
        run: |
          $env:PYTHONPATH = "$env:PYTHONPATH;$PWD"
          $env:EXPERIMENT_NAME="llm"
          $env:HOLDOUT_LOC="https://raw.githubusercontent.com/QuocHieu59/Made-With-ML/master/datasets/holdout.csv"
          python madewithml/evaluate.py --dataset-loc $env:HOLDOUT_LOC
